Added navbar UI main components
kabelic/crypto-app pull request #2
Opened 2022-11-25 23:46 UTC by kabelic

2022-11-25 23:48 UTC, kabelic commented
Hello bro, i finished 'Setup the Navbar' ticket from trello.
please you can review my code, i'm open to your feedback

2022-11-26 22:27 UTC, yoloOnTheBattlefield requested changes

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/components/coinsComponent/index.js
> +            <Link style={{textDecoration: 'none', color:'white'}} to='/coin'>Coins</Link>
don't use inline styles

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/components/coinsComponent/index.js
> +import {CoinStyle} from '../../components/styles/Nav.styled';
format your code

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/components/CurrencyComponent.js
> +import {RiArrowDropDownFill} from 'react-icons/ri'
format your code

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/App.js
> +import {createGlobalStyle, ThemeProvider} from 'styled-components'
format your code

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/App.js
>  import {Route, Routes} from 'react-router-dom'
format your code

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/App.js
> +import React from 'react';
move your abs imports at the top

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/App.js
> +    this.setState({on: !this.state.on})
format your code

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/App.js
> +        </>
no need for fragment

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/components/navComponent/NavComponent.js
> +import {SiNintendoswitch} from 'react-icons/si'
format your code
and abs imports at the top

2022-11-26 22:27 UTC, yoloOnTheBattlefield commented on src/components/searchComponent/index.js
> +import {RiSearch2Line} from 'react-icons/ri'
format your code
and move code at top

2022-11-27 19:50 UTC, merged