Coinpage
kabelic/crypto-app pull request #5
Opened 2022-12-15 17:15 UTC by kabelic

Fetch from api:
- bitcoin data
- ethereum
- dai

2022-12-15 18:01 UTC, yoloOnTheBattlefield requested changes

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/App.js
> +                  <Route path='/coin/ethereum' element={<Ethereum/>}/>
you should make the coin page dynamic, checkout how you did the weather app

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/BitcoinLeft.js
> +                }
you need to return null from map if the if statement bounces

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/Chart.js
> +        labels: UserData.map((data) => data.year),
use camelCase

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/Charts/LineChart.js
> +// import {Chart as ChartJS} from 'chart.js/auto'
remove commented out code

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/navComponent/NavComponent.js
> +                <CreateAccount bg={'#FFAF2C'} text={'Create a new account'}/>
don't use {} for strings

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/styles/Body.styled.js
> +   margin-left: ${({ margin }) => margin }px;
remove empty space

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/styles/Body.styled.js
> +   /* font-weight: ${(props) => props.size ? props.size : 500}; */
remove commented out code

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/styles/Nav.styled.js
> +    /* margin: 0 10px; */
remove commented out code

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/styles/Nav.styled.js
> +`
add new line

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/components/styles/coinpage.styled.js
> +    /* line-height: 35px; */
remove comments

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/pages/Ethereum.js
> +            const {data} = await axios('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=true&price_change_percentage=1h%2C24h%2C7d')
const {` `data` `}

2022-12-15 18:01 UTC, yoloOnTheBattlefield commented on src/pages/Ethereum.js
> +            <div style={{width: '100%'}}>
don't use inline styles

2022-12-16 05:19 UTC, kabelic commented on src/App.js
> +                  <Route path='/coin/ethereum' element={<Ethereum/>}/>
I haven't done weather app before. would you give me a hint?

2022-12-16 06:53 UTC, merged